// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCalculator: typeof import('~icons/carbon/calculator')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GgSpinner: typeof import('~icons/gg/spinner')['default']
    Header: typeof import('./components/Header.vue')['default']
    'HeroiconsOutline:check': typeof import('~icons/heroicons-outline/check')['default']
    'HeroiconsOutline:selector': typeof import('~icons/heroicons-outline/selector')['default']
    LangSelecator: typeof import('~icons/la/ng-selecator')['default']
    LangSelector: typeof import('./components/Header/LangSelector.vue')['default']
    README: typeof import('./components/README.md')['default']
    'Twemoji:flagForFlagBrazil': typeof import('~icons/twemoji/flag-for-flag-brazil')['default']
    'Twemoji:flagForFlagUnitedStates': typeof import('~icons/twemoji/flag-for-flag-united-states')['default']
  }
}

export { }
